# fly.toml app configuration
app = "potshotgg"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "server.Dockerfile"

[env]
  PORT = "8080"

# The [mounts] section has been REMOVED

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    port = 8080